@GamesCatalogAPI_HostAddress = http://localhost:5048

POST {{GamesCatalogAPI_HostAddress}}/User/
Content-Type: application/json
# Authorization: Bearer {{token}}
{
  "name": "test",
  "email": "user2@example.com",
  "password": "pass123"
}
###


