@GamesCatalogAPI_HostAddress = http://localhost:5048

POST {{GamesCatalogAPI_HostAddress}}/User/
Content-Type: application/json
{
  "name": "test",
  "email": "emanuel.xpe@gmail.com",
  "password": "pass123"
}
###

POST {{GamesCatalogAPI_HostAddress}}/User/Session
Content-Type: application/json
{
  "email": "emanuel.xpe@gmail.com",
  "password": "pass123"
}
###

POST {{GamesCatalogAPI_HostAddress}}/User/RecoverPassword
Content-Type: application/json
{
  "email": "user@example.com"
}
###

#Auths
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiI1IiwiZW1haWwiOiJlbWFudWVsLnhwZUBnbWFpbC5jb20iLCJuYmYiOjE3NDQ4Mzg2NjQsImV4cCI6MTc0NTI3MDY2NCwiaWF0IjoxNzQ0ODM4NjY0fQ.x_Q_a1PcGxgeduZFJZllNc7eGOZd1cKBfU7aHH9UQSg

GET {{GamesCatalogAPI_HostAddress}}/User
Authorization: Bearer {{Token}}
###

POST {{GamesCatalogAPI_HostAddress}}/Game/IGDB
Authorization: Bearer {{Token}}
Content-Type: application/json
{
  "Search": "god of war",
  "StartIndex": "0"
}
###